# Generated by Django 3.0.8 on 2020-07-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Delivering'), (1, 'Completed'), (2, 'Cancelled')], help_text='<ul><li>0 - Delivering</li><li>1 - Completed</li><li>Cancelled</li></ul>', max_length=1),
        ),
    ]
